### ISSUE TITLE
suggested improvements to README.md

### ISSUE THREAD

**Issue by kayvonf** [scanner-research/tv-news-ingest-pipeline#1]
1. Let's start the README.md with a short paragraph about what the scripts in this repo do.  The ingest video files and generate annotations needed for the TV news viewer (should probably link to that repo)

2. Odd that the README says all videos must show a particular naming convention, and then the video file in the subsequence example does not have a filename matching that convention.

3. The "tree" of output is a nice figure, but I think we should briefly summarize the content of each generated file.  (i.e., this is all the face detections)

4. Are the embeddings *really* stored in plaintest json?  Ouch!  That's going to be really large in file size.

**Comment by jeremyephron** [comment]
Updates to the README have been made that address these concerns.
